// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAuAmyqIBeHW7NsqDNMeuwN2VMZi4J5TY',
    appId: '1:725845336918:web:703f2d9432ea3c0cb06cf7',
    messagingSenderId: '725845336918',
    projectId: 'multiplex-storage',
    authDomain: 'multiplex-storage.firebaseapp.com',
    storageBucket: 'multiplex-storage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyzVXRhJiFayn4PaRYEZSjFhSNhydWqyY',
    appId: '1:725845336918:android:9265de9320f94ac3b06cf7',
    messagingSenderId: '725845336918',
    projectId: 'multiplex-storage',
    storageBucket: 'multiplex-storage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL3ovV9YsTIQUg1dYL-mWKvUarOzlMgf4',
    appId: '1:725845336918:ios:de1f3d5597b550f9b06cf7',
    messagingSenderId: '725845336918',
    projectId: 'multiplex-storage',
    storageBucket: 'multiplex-storage.appspot.com',
    iosClientId: '725845336918-el94eitcp91rphpaj94q0t32a143o51b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageMultiplex',
  );
}
